Repository BCDA-APS/mdaviz, pull requests merged in 2024-06, with the labels that each got.

#135 bug with underscore separator in file name
  mdaviz/data/test_folder1/nounderscoreprefix0008.mda
  mdaviz/data/test_folder1/prefix000001.mda
  mdaviz/data/test_folder1/prefix02.mda
  mdaviz/data/test_folder1/simple prefix 0007.mda
  mdaviz/data/test_folder1/some-other-prefix-00003.mda
  mdaviz/data/test_folder1/yet.anotherprefix.06.mda
  mdaviz/mda_folder_table_model.py
Labels: bug

#133 125 add command line options
  mdaviz/app.py
  mdaviz/mainwindow.py
  mdaviz/tests/test_app.py
Labels: enhancement

#140 Solve performance issues when loading folders
  .github/workflows/docs.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  docs/source/changes.rst
  docs/source/index.rst
  docs/source/license.rst
  mdaviz/LICENSE
  mdaviz/app.py
  mdaviz/chartview.py
  mdaviz/data_table_view.py
  mdaviz/mainwindow.py
  mdaviz/mda_file.py
  mdaviz/mda_file_table_model.py
  mdaviz/mda_file_table_view.py
  mdaviz/mda_file_viz.py
  mdaviz/mda_folder.py
  mdaviz/mda_folder_table_model.py
  mdaviz/mda_folder_table_view.py
  mdaviz/opendialog.py
  mdaviz/resources/first.svg
  mdaviz/resources/last.svg
  mdaviz/resources/mainwindow.ui
  mdaviz/resources/open.svg
  mdaviz/synApps_mdalib/LICENSE
  mdaviz/synApps_mdalib/METADATA
  mdaviz/synApps_mdalib/f_xdrlib.py
  mdaviz/synApps_mdalib/mda.py
  mdaviz/user_settings.py
  mdaviz/utils.py
  pyproject.toml
Labels: bug, enhancement

#149 Fix a few minor bugs
  mdaviz/chartview.py
  mdaviz/mda_file.py
  mdaviz/mda_folder.py
  mdaviz/utils.py
Labels: bug, enhancement

#151 57 user confirmation for large directories
  mdaviz/mainwindow.py
  mdaviz/mda_folder.py
  mdaviz/popup.py
  mdaviz/resources/popup.ui
Labels: enhancement

#153 #152 fixed!!!!
  mdaviz/mainwindow.py
Labels: bug

#155 DOC needs a suffix to match the file name
  LICENSE.txt
  docs/source/license.rst
Labels: documentation

#156 remove f_xrdlib.py
  mdaviz/synApps_mdalib/LICENSE
  mdaviz/synApps_mdalib/f_xdrlib.py
Labels: bug, task
