Repository BCDA-APS/mdaviz, pull requests merged in 2024-05, with the labels that each got.

#119 vendor the mdalib code
  env.yml
  mdaviz/mda_folder_table_model.py
  mdaviz/select_fields_table_view.py
  mdaviz/synApps_mdalib/LICENSE
  mdaviz/synApps_mdalib/METADATA
  mdaviz/synApps_mdalib/README.md
  mdaviz/synApps_mdalib/__init__.py
  mdaviz/synApps_mdalib/f_xdrlib.py
  mdaviz/synApps_mdalib/mda.py
  mdaviz/utils.py
Labels: task

#121 start unit testing
  .github/workflows/code.yml
  .github/workflows/pypi.yml
  mdaviz/tests/__init__.py
  mdaviz/tests/test_aboutdialog.py
  mdaviz/tests/test_app.py
Labels: enhancement

#116 update packaging to build wheel & source dist for PyPI uploads
  env.yml
  pyproject.toml
Labels: bug, task

#130 Update README.md
  README.md
Labels: documentation

#129 Update documentation
  docs/source/_static/mdaviz_gui.png
  docs/source/api/mda_file_table_model.rst
  docs/source/api/mda_file_table_view.rst
  docs/source/api/select_fields_table_model.rst
  docs/source/changes.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/license.rst
  mdaviz/data_table_model.py
  mdaviz/mda_file_table_model.py
  mdaviz/mda_file_table_view.py
  mdaviz/utils.py
Labels: documentation
